package com.admin.entity;

/**
 * ACity generated by hbm2java
 */
public class EpCity implements java.io.Serializable {

	/** */
	/**
	* ID.
	*/
	private Integer cityId;
	/** */
	/**
	* 省市区名称.
	*/
	private String cityName;
	/** */
	/**
	* 上级ID'.
	*/
	private EpCity cityParentid;
	/** */
	/**
	* 简称.
	*/
	private String cityShortname;
	/** */
	/**
	* 级别:0,中国；1，省分；2，市；3，区、县'.
	*/
	private Integer cityLeveltype;
	/** */
	/**
	* 城市代码.
	*/
	private String cityCode;
	/** */
	/**
	* 邮编.
	*/
	private String cityZipcode;
	/** */
	/**
	* 精度.
	*/
	private String cityLng;
	/** */
	/**
	* 维度.
	*/
	private String cityLat;
	/** */
	/**
	* 拼音.
	*/
	private String cityPinyin;
	/** */
	/**
	* 0 失效 1 有效.
	*/
	private Integer cityStates;
	
	public static String getLevelName(Integer cityLevelType){
		switch (cityLevelType) {
		case 0:
			return "中国";
		case 1:
			return "省份";
		case 2:
			return "市";
		case 3:
			return "区、县";
		default:
			return cityLevelType+"";
		}
	}
	
	public EpCity() {
	}

	public EpCity(Integer cityId) {
		this.cityId = cityId;
	}

	public EpCity(Integer cityId, String cityName, EpCity cityParentid, String cityShortname, Integer cityLeveltype,
			String cityCode, String cityZipcode, String cityLng, String cityLat, String cityPinyin,
			Integer cityStates) {
		this.cityId = cityId;
		this.cityName = cityName;
		this.cityParentid = cityParentid;
		this.cityShortname = cityShortname;
		this.cityLeveltype = cityLeveltype;
		this.cityCode = cityCode;
		this.cityZipcode = cityZipcode;
		this.cityLng = cityLng;
		this.cityLat = cityLat;
		this.cityPinyin = cityPinyin;
		this.cityStates = cityStates;
	}

	/**  
	 * 鍙栧緱 ID.
	 */
	public Integer getCityId() {
		return this.cityId;
	}

	/**
	 * 璁剧疆 ID.
	 */
	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	/**  
	 * 鍙栧緱 省市区名称.
	 */
	public String getCityName() {
		return this.cityName;
	}

	/**
	 * 璁剧疆 省市区名称.
	 */
	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	/**  
	 * 鍙栧緱 上级ID'.
	 */
	public EpCity getCityParentid() {
		return this.cityParentid;
	}

	/**
	 * 璁剧疆 上级ID'.
	 */
	public void setCityParentid(EpCity cityParentid) {
		this.cityParentid = cityParentid;
	}

	/**  
	 * 鍙栧緱 简称.
	 */
	public String getCityShortname() {
		return this.cityShortname;
	}

	/**
	 * 璁剧疆 简称.
	 */
	public void setCityShortname(String cityShortname) {
		this.cityShortname = cityShortname;
	}

	/**  
	 * 鍙栧緱 级别:0,中国；1，省分；2，市；3，区、县'.
	 */
	public Integer getCityLeveltype() {
		return this.cityLeveltype;
	}

	/**
	 * 璁剧疆 级别:0,中国；1，省分；2，市；3，区、县'.
	 */
	public void setCityLeveltype(Integer cityLeveltype) {
		this.cityLeveltype = cityLeveltype;
	}

	/**  
	 * 鍙栧緱 城市代码.
	 */
	public String getCityCode() {
		return this.cityCode;
	}

	/**
	 * 璁剧疆 城市代码.
	 */
	public void setCityCode(String cityCode) {
		this.cityCode = cityCode;
	}

	/**  
	 * 鍙栧緱 邮编.
	 */
	public String getCityZipcode() {
		return this.cityZipcode;
	}

	/**
	 * 璁剧疆 邮编.
	 */
	public void setCityZipcode(String cityZipcode) {
		this.cityZipcode = cityZipcode;
	}

	/**  
	 * 鍙栧緱 精度.
	 */
	public String getCityLng() {
		return this.cityLng;
	}

	/**
	 * 璁剧疆 精度.
	 */
	public void setCityLng(String cityLng) {
		this.cityLng = cityLng;
	}

	/**  
	 * 鍙栧緱 维度.
	 */
	public String getCityLat() {
		return this.cityLat;
	}

	/**
	 * 璁剧疆 维度.
	 */
	public void setCityLat(String cityLat) {
		this.cityLat = cityLat;
	}

	/**  
	 * 鍙栧緱 拼音.
	 */
	public String getCityPinyin() {
		return this.cityPinyin;
	}

	/**
	 * 璁剧疆 拼音.
	 */
	public void setCityPinyin(String cityPinyin) {
		this.cityPinyin = cityPinyin;
	}

	/**  
	 * 鍙栧緱 0 失效 1 有效.
	 */
	public Integer getCityStates() {
		return this.cityStates;
	}

	/**
	 * 璁剧疆 0 失效 1 有效.
	 */
	public void setCityStates(Integer cityStates) {
		this.cityStates = cityStates;
	}

}
